"""
Reads the metrics files generated by R, and 
generates density plots, histograms, correlation plots etc.
"""

import numpy as np
import pandas as pd
import os

def read(sheet_ID, C):
	DATA = pd.read_csv(sheet_ID, usecols=info_columns, header=True)
	return DATA


DC   = '/Users/apple/Documents/Network_Analysis/Playground/output/metrics/metrics_R_DC_F13.csv'
SCDR = '/Users/apple/Documents/Network_Analysis/Playground/output/metrics/metrics_R_SCDR_F14.csv'
SCSR = '/Users/apple/Documents/Network_Analysis/Playground/output/metrics/metrics_R_SCSR_F09.csv'
total 64
-rw-r--r--  1 apple  staff  1176 Apr 20 16:02 metrics_R_DC_F05.csv
-rw-r--r--@ 1 apple  staff  1535 Apr 20 16:02 metrics_R_DC_F13.csv
-rw-r--r--  1 apple  staff  1497 Apr 20 16:02 metrics_R_SCDR_F01.csv
-rw-r--r--  1 apple  staff  1314 Apr 20 16:02 metrics_R_SCDR_F12.csv
-rw-r--r--  1 apple  staff  1514 Apr 20 16:02 metrics_R_SCDR_F14.csv
-rw-r--r--  1 apple  staff  1501 Apr 20 16:02 metrics_R_SCSR_F08.csv
-rw-r--r--  1 apple  staff  1491 Apr 20 16:02 metrics_R_SCSR_F09.csv
-rw-r--r--  1 apple  staff  1380 Apr 20 16:02 metrics_R_SCSR_F11.csv
Sohams-MBP:metrics apple$ pwd
