#============================================================================
# SM 3/2017
# Code to generate network visualisations of the graph level indices
# 	> heatmap of association matrix, network, community structure.
# 	> Reads the association matrix generated by python scripts.
# 	> community detection, color vertices by side.
#============================================================================

library(igraph)
library(viridis)
library(gplots)
library(ggplot2)
library(reshape2)
library(car)

rm(list = ls())
gc()

# Main function: process graphs here. 
generate_GRAPH <- function(file)
{
	ADJ   <- read.csv(file, header=F)
	ADJ   <- as.matrix(ADJ)
	G     <- graph.adjacency(ADJ, mode="directed", weight=TRUE)
	GRAPH <- simplify(G, remove.multiple = F, remove.loops = T)
}

compute_motifs <- function(GRAPH, ID)
{
	TRIADS <- as.matrix(triad.census(GRAPH))
	DYADS  <- as.matrix(dyad.census(GRAPH))
	CENSUS <- rbind(DYADS, TRIADS)

	write.table(CENSUS, file = sprintf('../../output/network/motifs/motifs_%s.txt', gsub(".csv", "", ID)), sep="\t", row.names=FALSE, col.names=FALSE)
}

compute_metrics <- function(GRAPH, ID)
{

	TRANSITIVITY <- as.vector(transitivity(GRAPH, type="weighted", isolates='zero')) #giving NaN's
	BETWEENNESS <- as.vector(betweenness(GRAPH, v=V(GRAPH), directed = TRUE, weights = E(GRAPH)$weight, nobigint = TRUE, normalized = FALSE))
	NODE_STRENGTH  <- as.vector(graph.strength(GRAPH, mode = 'all', weights = E(GRAPH)$weight))
	EIGENVECTOR <- as.vector(evcent(GRAPH, scale = TRUE, weights = E(GRAPH)$weight)$vector)

	METRICS <- cbind(seq(1,40,1), TRANSITIVITY, BETWEENNESS, NODE_STRENGTH,EIGENVECTOR)
	colnames(METRICS) <- c("ID","TRANSITIVITY", "BETWEENNESS", "NODE_STRENGTH", "EIGENVECTOR")
	write.table(METRICS, file = sprintf('../../output/network/metrics/metrics_%s.csv', gsub(".csv", "", ID)), sep=",", row.names=FALSE)
	RESULT <- METRICS
}

plot_heatmaps <- function(GRAPH, CC, ID)
{

	pallete <- viridis(500.0, alpha = 1, begin = 0, end = 1, option = "D")
	HEATMAP <- get.adjacency(GRAPH, attr="weight", sparse=F)

	colnames(HEATMAP) <- CC$code
	rownames(HEATMAP) <- CC$code

	pdf(file = sprintf('../../output/visualisations/heatmaps/%s.pdf', gsub(".csv", "", ID)))

	heatmap.2(HEATMAP, Rowv=NULL,Colv=NULL,
		col = pallete,
		scale="none",
		margins=c(3,0),
		trace='none',
		dendrogram='none',
		density.info='none',
		keysize=1,
		key.par=list(mar=c(3.5,0,3,0)),
		lmat=rbind(c(5, 4, 2), c(6, 1, 3)), lhei=c(1.0, 5), lwid=c(1, 10, 1))

	dev.off()
}

plot_network <- function(GRAPH, CC, ID, layout)
{
	colrs <- rep(c('darkseagreen','mediumpurple3'), each=20)
	l <- layout
	m <- layout
	scaling <- 4.0
	V(GRAPH)$color <- colrs[V(GRAPH)]

	NODE_STRENGTH  <- as.vector(graph.strength(GRAPH, mode = 'all', weights = E(GRAPH)$weight))
	V(GRAPH)$size=NODE_STRENGTH*4.0 + 2.2

	E(GRAPH)$width <- E(GRAPH)$weight*3.0

	pdf(file = sprintf('../../output/visualisations/networks/%s.pdf', gsub(".csv", "", ID)))

	plot(GRAPH,
		edge.arrow.size=.45,
		edge.color='darkslategrey',
		vertex.label=NA,
		vertex.color=V(GRAPH)$color,
		vertex.frame.color=NA,
		layout=l*scaling)

	title(sprintf('%s', gsub(".csv", "", ID)),cex.main=0.8, col.main="darkslategrey")
	mtext(sprintf('Density : %s', graph.density(GRAPH)), side=1, cex = 0.7 )
	dev.off()
}

plot_community<- function(GRAPH, CC, ID, layout)
{
	colrs <- rep(c('darkseagreen','mediumpurple3'), each=20)
	l <- layout
	m <- layout
	scaling <- 4.0
	V(GRAPH)$color <- colrs[V(GRAPH)]
	E(GRAPH)$width <- E(GRAPH)$weight*3.0

	NODE_STRENGTH  <- as.vector(graph.strength(GRAPH, mode = 'all', weights = E(GRAPH)$weight))
	V(GRAPH)$size=NODE_STRENGTH*4.0 + 2.2

	COMMUNITY <- edge.betweenness.community (GRAPH, weights = E(GRAPH)$weight,
    directed = TRUE, edge.betweenness = TRUE, modularity = TRUE, membership = TRUE)

	pdf(file = sprintf('../../output/visualisations/communities/%s.pdf', gsub(".csv", "", ID)))

	plot(COMMUNITY, GRAPH,
		edge.arrow.size=.45,
		edge.color='darkslategrey',
	 	vertex.label=NA,
	 	col = colrs,
		vertex.frame.color=NA,
		layout=l*scaling,
		mark.col = rainbow(length(membership(COMMUNITY)), alpha = 0.1),
		mark.border = 0.6)

	title(sprintf('%s', gsub(".csv", "", ID)), cex.main=0.8, col.main="darkslategrey")
	mtext(sprintf('Density : %s  Modularity : %s', graph.density(GRAPH), modularity(COMMUNITY)), side=1, cex = 0.7)
	dev.off()
}

#=================================================================
# Control Panel
#=================================================================

system("mkdir -p ../../output/visualisations/heatmaps")
system("mkdir -p ../../output/visualisations/networks")
system("mkdir -p ../../output/visualisations/communities")

system("mkdir -p ../../output/network/metrics")
system("mkdir -p ../../output/network/motifs")

CC <- read.csv("../../datasets/info/color_coding.csv")
path = '../../output/csv/ADJ'
file.names <- dir(path, pattern =".csv")

for (i in 1:length(file.names))
{	
	file = sprintf('../../output/csv/ADJ/%s', file.names[i])
	GRAPH <- generate_GRAPH(file)
	layout <- layout.fruchterman.reingold(GRAPH)

	plot_heatmaps(GRAPH, CC, file.names[i])
	plot_network(GRAPH, CC, file.names[i], layout)
	plot_community(GRAPH, CC, file.names[i], layout)
	
	compute_motifs(GRAPH, file.names[i])
	compute_metrics(GRAPH, file.names[i])
}

