#============================================================================
# Code to generate network visualisations of the graph level indices
# 	> heatmap of association matrix, network, community structure.
# 	> Reads the association matrix generated by python scripts.
# 	> community detection, color vertices by side.

# Soham Mukherjee 3/2017
#============================================================================

library(igraph)
library(viridis)
library(gplots)
library(ggplot2)
library(reshape2)
library(car)

rm(list = ls())
gc()

generate_GRAPH <- function(file, CC, ID)
{
	ADJ   <- as.matrix(read.csv(file, header=F))
	GRAPH <- graph.adjacency(ADJ, mode="directed", weight=TRUE)
	GRAPH <- simplify(GRAPH, remove.multiple = F, remove.loops = TRUE)
	GRAPH <- set_vertex_attr(GRAPH, "RETREAT", value=rep(c('gray8','gray87'), each=20))

	cat("\nWokring on file:", file)
	GRAPH  <- delete.vertices(GRAPH, degree(GRAPH)==0)		# delete isolates
}

#=================================================================
# Control Panel
#=================================================================

# make directories to store the output
system("mkdir -p ../../output/network/graph")

# read the location of the files and the the location for the color codes.
CC <- read.csv("../../datasets/info/color_coding.csv")
file.names <- dir('../../output/csv/ADJ', pattern ="*.csv")

LDN <- c()
LID <- c()

for (i in 1:length(file.names))
{	
	file    <- sprintf('../../output/csv/ADJ/%s', file.names[i])
	GRAPH   <- generate_GRAPH(file, CC, file.names[i])
	DENSITY <- edge_density(GRAPH, loops=TRUE)  

	LDN  <- c(LDN, DENSITY)
	LID  <- c(LID, gsub(".csv", "", file.names[i]))
}	

ADENSITY <- cbind(LID, LDN)
colnames(ADENSITY) <- c("FRAME ID", "DENSITY")
write.table(ADENSITY, file = sprintf('../../output/network/graph/density.csv'), sep=",", row.names=FALSE)
cat("\n")
