#============================================================================
# Code to generate network visualisations of the graph level indices
# 	> heatmap of association matrix, network, community structure.
# 	> Reads the association matrix generated by python scripts.
# 	> community detection, color vertices by side.

# Soham Mukherjee 3/2017
#============================================================================

library(igraph)
library(viridis)
library(gplots)
library(ggplot2)
library(reshape2)
library(car)

rm(list = ls())
gc()

generate_GRAPH <- function(file, CC, ID)
{
	ADJ   <- as.matrix(read.csv(file, header=F))
	GRAPH <- graph.adjacency(ADJ, mode="directed", weight=TRUE)
	GRAPH <- simplify(GRAPH, remove.multiple = F, remove.loops = TRUE)
	GRAPH <- set_vertex_attr(GRAPH, "RETREAT", value=rep(c('gray8','gray87'), each=20))
	# plot_heatmaps(GRAPH, CC, ID)
	cat("\nWokring on file:", file)
	GRAPH  <- delete.vertices(GRAPH, degree(GRAPH)==0)		# delete isolates
	layout <- layout.fruchterman.reingold(GRAPH)
	plot_network(GRAPH, file.names[i], layout)
}

plot_heatmaps <- function(GRAPH, CC, ID)
{
	pallete <- viridis(500.0, alpha = 1, begin = 0, end = 1, option = "D")
	HEATMAP <- get.adjacency(GRAPH, attr="weight", sparse=F)

	colnames(HEATMAP) <- CC$code
	rownames(HEATMAP) <- CC$code

	pdf(file = sprintf('../../output/visualisations/heatmaps/%s.pdf', gsub(".csv", "", ID)))

	heatmap.2(HEATMAP, Rowv=NULL,Colv=NULL,
		col = pallete,
		scale="none",
		margins=c(3,0),
		trace='none',
		dendrogram='none',
		density.info='none',
		keysize=1,
		key.par=list(mar=c(3.5,0,3,0)),
		lmat=rbind(c(5, 4, 2), c(6, 1, 3)), lhei=c(1.0, 5), lwid=c(1, 10, 1))

	dev.off()
}

plot_network <- function(GRAPH, ID, layout)
{
	l <- layout
	scaling <- 58.0
	normalize <- function(x) {x / sqrt(sum(x^2))}

	NODE_STRENGTH  <- as.vector(degree(GRAPH, mode = 'total'))
	V(GRAPH)$size  <- normalize(NODE_STRENGTH)*30.0 + 2.0
	E(GRAPH)$width <- normalize(E(GRAPH)$weight)*3.0 + 0.2

	# pdf(file = sprintf('../../output/visualisations/networks/%s.pdf', gsub(".csv", "", ID)))
	# <see https://www.r-bloggers.com/high-resolution-figures-in-r/>
	png(file = sprintf('../../output/visualisations/networks/%s.png', gsub(".csv", "", ID)), 
		width = 14, height = 14, units = 'cm', res = 300)

	plot(GRAPH,
		edge.arrow.size=.25,
		edge.color='grey8',
		vertex.label=NA,
		vertex.color=V(GRAPH)$RETREAT,
		vertex.frame.color='darkslategrey',
		layout=l*scaling)

	treatment <- strsplit(ID, "_")[[1]][3]
	frame     <- strsplit(ID, "_")[[1]][4]
	if (treatment== "SCDR") {
	   string <- "Same Colony Different Retreat"
	} else if (treatment== "SCSR") {
		string <- "Same Colony Same Retreat"
	} else if (treatment== "DC") {
		string <- "Different Colony"
	}

	title(sprintf('%s', string), cex.main=0.8, font.main=1, col.main="darkslategrey")
	mtext(sprintf('%s', gsub(".csv", "", frame)), line=2, side=3, cex=0.7, adj = 1)
	dev.off()
}


plot_community<- function(GRAPH, ID, layout)
{
	l <- layout
	scaling <- 4.0
	normalize <- function(x) {x / sqrt(sum(x^2))}

	NODE_STRENGTH  <- as.vector(degree(GRAPH, mode = 'total'))
	V(GRAPH)$size  <- normalize(NODE_STRENGTH)*30.0 + 100.0
	E(GRAPH)$width <- normalize(E(GRAPH)$weight)*3.0

	COMMUNITY <- edge.betweenness.community(GRAPH, weights = E(GRAPH)$weight,
    directed = TRUE, edge.betweenness = TRUE, modularity = TRUE, membership = TRUE)

	pdf(file = sprintf('../../output/visualisations/communities/%s.pdf', gsub(".csv", "", ID)))

	plot(COMMUNITY, GRAPH,
		edge.arrow.size=.45,
		edge.color='darkslategrey',
	 	vertex.label=NA,
	 	vertex.color=V(GRAPH)$RETREAT,
		vertex.frame.color=NA,
		layout=l*scaling,
		mark.col = rainbow(length(membership(COMMUNITY)), alpha = 0.00001))

	treatment <- strsplit(ID, "_")[[1]][3]
	frame     <- strsplit(ID, "_")[[1]][4]
	if (treatment== "SCDR") {
	   string <- "Same Colony Different Retreat"
	}
	title(sprintf('%s', string), cex.main=0.8, font.main=1, col.main="darkslategrey")
	mtext(sprintf('%s', gsub(".csv", "", frame)), line=2, side=3, cex=0.7, adj = 1)
	dev.off()
}

#=================================================================
# Control Panel
#=================================================================

# make directories to store the output
system("mkdir -p ../../output/visualisations/heatmaps")
system("mkdir -p ../../output/visualisations/networks")
system("mkdir -p ../../output/visualisations/communities")
system("mkdir -p ../../output/network/metrics")
system("mkdir -p ../../output/network/motifs")

# read the location of the files and the the location for the color codes.
CC <- read.csv("../../datasets/info/color_coding.csv")
file.names <- dir('../../output/csv/ADJ', pattern ="*.csv")

for (i in 1:length(file.names))
{	
	file   <- sprintf('../../output/csv/ADJ/%s', file.names[i])
	GRAPH  <- generate_GRAPH(file, CC, file.names[i])
}	
cat("\n")
